services:
    payment.bridge:
        class: Maozedong\PaymentBridgeBundle\Services\PaymentBridge

    payment.event.listener:
            class:     Maozedong\PaymentBridgeBundle\EventListener\Payment
            arguments: [@doctrine.orm.entity_manager, @mailer]
            tags:
                - { name: kernel.event_listener, event: payment.order.done, method: onPaymentOrderDone }
                - { name: kernel.event_listener, event: payment.order.created, method: onPaymentOrderCreated }
                - { name: kernel.event_listener, event: payment.order.load, method: onPaymentOrderLoad }
                - { name: kernel.event_listener, event: payment.order.success, method: onPaymentSuccess }
                - { name: kernel.event_listener, event: payment.order.fail, method: onPaymentFail }




#parameters:
#    maozedong_payment_bridge.example.class: Maozedong\PaymentBridgeBundle\Example

#services:
#    maozedong_payment_bridge.example:
#        class: %maozedong_payment_bridge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
