maozedong_security_test_homepage:
    pattern:  /
    defaults: { _controller: MaozedongSecurityTestBundle:Default:index }

maozedong_security_test_cart_view:
    pattern:  /cart_view
    defaults: { _controller: MaozedongSecurityTestBundle:Default:cartView }

maozedong_security_test_homepage:
    pattern:  /
    defaults: { _controller: MaozedongSecurityTestBundle:Default:index }